import { RoleGate } from "@/components/RoleGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AlertCircle, ArrowRight, BookMarked, CheckCheck, ClipboardList, Eye, Gauge, HelpCircle, TimerReset } from "lucide-react";
import { useLocation } from "wouter";

const exerciseTypes = ["اختيار متعدد", "اختيارات متعددة", "صح أو خطأ", "ملء", "مطابقة", "ترتيب", "قيمة رقمية", "تعبير رياضي", "إجابة قصيرة", "متعدد الخطوات", "تحليل وثيقة", "صورة تفاعلية"];
const errorAreas = ["المفهوم", "الإشارة", "الطريقة", "التعويض", "الوحدة", "الاستنتاج"];
export default function AssessmentLab() { return <RoleGate allowed={["student"]} title="محرك التمارين محمي"><AssessmentContent /></RoleGate>; }
function AssessmentContent() { const [, setLocation] = useLocation(); return <div className="min-h-screen bg-[#f6f8ff] p-5 sm:p-8" dir="rtl"><main className="mx-auto max-w-6xl"><button onClick={() => setLocation("/app")} className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowRight className="h-4 w-4"/>لوحة التعلم</button><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker">التدريب والتصحيح</p><h1 className="mt-2 text-3xl font-black text-slate-950">مش مهم تعرف فقط أنك غلطت.</h1><p className="mt-2 text-sm text-slate-600">المحرك يربط المحاولة ونوع الخطأ والتلميحات والمراجعة القادمة.</p></div><Badge className="border-0 bg-amber-50 px-3 py-2 text-amber-700 hover:bg-amber-50">بانتظار محتوى معتمد</Badge></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_.8fr]"><section className="soft-panel p-6"><div className="flex items-center justify-between"><div><p className="font-black">بنك أنواع التمارين</p><p className="mt-1 text-xs text-slate-500">سجل موحد لتصميم السؤال وإجابته وتحليله.</p></div><ClipboardList className="h-5 w-5 text-blue-700"/></div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-3">{exerciseTypes.map(type => <div key={type} className="rounded-xl border border-slate-100 bg-slate-50 px-3 py-3 text-center text-xs font-bold text-slate-600">{type}</div>)}</div></section><section className="rounded-[1.5rem] bg-blue-950 p-6 text-white"><div className="flex items-center gap-2 text-cyan-200"><HelpCircle className="h-5 w-5"/><p className="font-black">محرك التلميحات</p></div><div className="mt-6 space-y-3"><Hint n="1" text="وجّه الانتباه إلى المعطى أو المفهوم."/><Hint n="2" text="اقترح خطوة أو علاقة مناسبة."/><Hint n="3" text="اكشف بنية الحل دون قفز للجواب."/><Hint n="4" text="الحل خطوة بخطوة بعد الاختيار."/></div></section></div><section className="mt-6 grid gap-5 md:grid-cols-3"><Mini icon={AlertCircle} title="لماذا أخطأت؟" text="تصنيف بحسب المادة: مفهوم، طريقة، وحدة، استنتاج وغيرها."/><Mini icon={BookMarked} title="دفتر الأخطاء" text="يحفظ التكرار والتفسير ويربطه بالمراجعة."/><Mini icon={TimerReset} title="مراجعة متباعدة" text="تُقدم ما يحتاج تثبيتًا في الوقت المناسب."/></section><section className="mt-6 rounded-[1.5rem] border border-blue-100 bg-white p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">حالات الإتقان</p><div className="mt-4 flex flex-wrap gap-2">{["نبدأ", "نفهم", "نتدرب", "قريب من الإتقان", "متقن"].map((state, index) => <span key={state} className={`rounded-xl px-3 py-2 text-xs font-black ${index === 0 ? "bg-slate-100 text-slate-700" : index === 4 ? "bg-emerald-100 text-emerald-700" : "bg-blue-50 text-blue-700"}`}>{state}</span>)}</div></div><div className="text-sm leading-6 text-slate-500"><Gauge className="mb-2 h-5 w-5 text-blue-700"/>لا يحسب الإتقان بمجرد مشاهدة الشرائح؛ بل من الدقة والصعوبة والمحاولات والتلميحات والمراجعة.</div></div></section></main></div>; }
function Hint({ n, text }: { n: string; text: string }) { return <div className="flex items-center gap-3 rounded-xl bg-white/10 p-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-cyan-300 text-xs font-black text-blue-950">{n}</span><p className="text-xs leading-5 text-blue-100">{text}</p></div>; }
function Mini({ icon: Icon, title, text }: { icon: typeof AlertCircle; title: string; text: string }) { return <div className="soft-panel p-5"><Icon className="h-5 w-5 text-rose-600"/><p className="mt-4 font-black">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>; }
