import { ScientificCanvas } from "@/components/ScientificCanvas";
import { LandingNarrative } from "@/components/LandingNarrative";
import { useScrollReveal } from "@/hooks/useScrollReveal";
import { Button } from "@/components/ui/button";
import { uxCopy } from "@/content/uxCopy";
import { useTheme } from "@/contexts/ThemeContext";
import React from "react";
import { ArrowLeft, BrainCircuit, CheckCircle2, ChevronLeft, CircleAlert, FlaskConical, FunctionSquare, Leaf, Moon, Sparkles, Sun, Target, TimerReset } from "lucide-react";
import { useLocation } from "wouter";

const subjects = [
  { title: "الرياضيات", note: "الدقة والمنطق", icon: FunctionSquare, className: "subject-math" },
  { title: "الفيزياء", note: "الطاقة والتجربة", icon: FlaskConical, className: "subject-physics" },
  { title: "العلوم", note: "الحياة والترابط", icon: Leaf, className: "subject-sciences" },
];

export default function Home() {
  useScrollReveal();
  const [, setLocation] = useLocation();
  const { theme, setTheme } = useTheme();
  return <div className="student-shell landing-shell overflow-hidden" dir="rtl">
    <header className="landing-header mx-auto flex h-20 max-w-[1360px] items-center justify-between px-5 sm:px-8"><button onClick={() => setLocation("/")} className="landing-brand"><span><Sparkles className="h-4 w-4" /></span><div><b>{uxCopy.brand.name}</b><small>بكالوريا الجزائر · 2027</small></div></button><nav className="landing-nav hidden items-center md:flex" aria-label="التنقل الرئيسي"><button onClick={() => setLocation("/subjects")}>المواد</button><button onClick={() => setLocation("/lab")}>التعلّم</button><button onClick={() => setLocation("/assessment")}>التدريب</button><button onClick={() => setLocation("/hassem")}>المراجعة</button><button onClick={() => setLocation("/bac")}>BAC Mode</button><button onClick={() => document.getElementById("plans")?.scrollIntoView({ behavior: "smooth" })}>الباقات</button></nav><div className="flex items-center gap-2"><button onClick={() => setTheme?.(theme === "dark" ? "light" : "dark")} className="student-icon-button" aria-label="تغيير السمة">{theme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</button><Button onClick={() => setLocation("/app")} className="student-button h-10 rounded-xl px-4 text-xs font-black">ابدأ مجانًا</Button></div></header>
    <main><section className="landing-hero mx-auto grid max-w-[1280px] gap-8 px-5 pb-16 pt-8 sm:px-8 lg:min-h-[610px] lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-14 lg:pb-20 lg:pt-12"><div className="landing-copy-block"><p className="student-eyebrow"><Sparkles className="h-3.5 w-3.5" /> {uxCopy.home.eyebrow}</p><div className="landing-title-mark mt-5" aria-hidden="true"><span>01</span><i /></div><h1 className="landing-title mt-4 font-black">{uxCopy.home.title}<span className="landing-title-accent">{uxCopy.home.accentTitle}</span></h1><p className="landing-copy mt-5">{uxCopy.home.description}</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => setLocation("/diagnostic")} className="student-button h-12 rounded-2xl px-5 font-black">{uxCopy.home.primaryCta} <ArrowLeft className="mr-2 h-4 w-4" /></Button><Button onClick={() => setLocation("/app")} variant="ghost" className="h-12 rounded-2xl border border-[var(--student-border)] px-5 font-black text-[var(--student-ink)] hover:bg-[var(--student-surface-2)]">{uxCopy.home.secondaryCta}</Button></div><div className="landing-proof mt-8"><span><CheckCircle2 />فكرة واضحة</span><span><CheckCircle2 />تدريب موجه</span><span><CheckCircle2 />مراجعة في وقتها</span></div></div><ScientificCanvas /></section>
      <section className="landing-steps"><div className="mx-auto grid max-w-[1280px] gap-5 px-5 py-8 sm:grid-cols-3 sm:px-8"><LandingStep n="01" title="شاهد الصورة" text="افهم السياق أولًا." /><LandingStep n="02" title="جرّب طريقتك" text="فكّر ثم أجب." /><LandingStep n="03" title="ثبّت السبب" text="راجع الخطأ في وقته." /></div></section><LandingNarrative onNavigate={setLocation} />
      <section className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="student-eyebrow">{uxCopy.home.subjectsEyebrow}</p><h2 className="landing-section-title mt-3 text-3xl font-black">{uxCopy.home.subjectsTitle}</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{subjects.map(subject => <button key={subject.title} onClick={() => setLocation("/subjects")} className={`student-surface student-card-interactive ${subject.className} rounded-[1.6rem] p-5 text-right`}><div className="subject-icon grid h-11 w-11 place-items-center rounded-2xl"><subject.icon className="h-5 w-5" /></div><p className="mt-7 text-xs font-black text-[var(--subject)]">{subject.note}</p><h3 className="mt-2 text-lg font-black">{subject.title}</h3><span className="mt-5 inline-flex items-center text-xs font-black student-muted">اكتشف المسار <ChevronLeft className="mr-1 h-3.5 w-3.5 text-[var(--subject)]" /></span></button>)}</div></section>
      <section className="landing-story mx-auto grid max-w-[1280px] gap-8 px-5 pb-20 sm:px-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="student-eyebrow">{uxCopy.home.errorEyebrow}</p><h2 className="landing-section-title mt-4 text-3xl font-black">{uxCopy.home.errorTitle}</h2><p className="mt-5 text-sm leading-8 student-muted">كل محاولة تترك لك خطوة أوضح.</p><Button onClick={() => setLocation("/app")} variant="ghost" className="mt-6 rounded-xl border border-[var(--student-border)] font-black text-[var(--student-primary)] hover:bg-[var(--student-glow)]">رتّب خطوتك</Button></div><div className="landing-story-card rounded-[2rem] p-6 sm:p-8"><p className="text-xs font-black text-rose-300">تحتاج مراجعة</p><p className="mt-3 text-lg font-black">«حدّد المعطيات أولًا.»</p><div className="my-6 h-px bg-white/10" /><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/6 p-4"><p className="text-xs font-black text-amber-300">نراجع</p><p className="landing-card-copy mt-2 text-xs">العلاقة قبل الحساب.</p></div><div className="rounded-2xl bg-white/6 p-4"><p className="text-xs font-black text-emerald-300">الخطوة التالية</p><p className="landing-card-copy mt-2 text-xs">بطاقة قصيرة في وقتها.</p></div></div></div></section>
      <section className="landing-diagnostic mx-auto max-w-[1280px] px-5 pb-20 sm:px-8"><div className="rounded-[2rem] p-6 sm:p-9"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-end"><div><p className="student-eyebrow"><Target className="h-3.5 w-3.5" /> تشخيص مجاني</p><h2 className="mt-4 text-2xl font-black sm:text-3xl">{uxCopy.home.diagnosticTitle}</h2><p className="mt-3 max-w-2xl text-sm leading-7 student-muted">{uxCopy.home.diagnosticDescription}</p></div><Button onClick={() => setLocation("/diagnostic")} className="student-button h-12 rounded-2xl px-5 font-black">ابدأ التشخيص <ArrowLeft className="mr-2 h-4 w-4" /></Button></div></div></section>
      <section className="landing-hassem mx-auto max-w-[1280px] px-5 pb-20 sm:px-8"><div className="flex flex-col gap-6 rounded-[2rem] p-6 sm:p-9 md:flex-row md:items-center md:justify-between"><div><p className="student-eyebrow">{uxCopy.hassem.eyebrow}</p><h2 className="landing-section-title mt-3 text-2xl font-black">{uxCopy.home.hassemTitle}</h2><p className="mt-3 max-w-xl text-sm leading-8 text-violet-100/85">{uxCopy.home.hassemDescription}</p></div><Button onClick={() => setLocation("/hassem")} variant="ghost" className="rounded-xl border border-amber-300/25 bg-amber-300/10 px-5 font-black text-amber-200 hover:bg-amber-300/15 hover:text-amber-100"><TimerReset className="ml-2 h-4 w-4" />{uxCopy.hassem.primaryCta}</Button></div></section>
      <section className="mx-auto max-w-[1280px] px-5 pb-16 text-center sm:px-8"><div className="inline-flex items-center gap-2 rounded-full border border-[var(--student-border)] bg-[var(--student-surface)] px-4 py-2 text-xs student-muted"><CircleAlert className="h-3.5 w-3.5 text-amber-400" />المحتوى الأكاديمي لا يُنشر قبل المرور على بوابة المصدر والمراجعة البشرية.</div></section>
    </main><footer className="border-t border-[var(--student-border)] px-5 py-8 text-center text-xs student-muted">{uxCopy.brand.name} · {uxCopy.brand.tagline} · 2026–2027</footer>
  </div>;
}

function LandingStep({ n, title, text }: { n: string; title: string; text: string }) { return <div className="flex items-start gap-4"><span className="landing-step-number">{n}</span><div><p className="font-black">{title}</p><p className="mt-1 text-xs leading-5 student-muted">{text}</p></div></div>; }
