import { MathBlock } from "@/components/MathBlock";
import { MindMapCanvas } from "@/components/MindMapCanvas";
import { RoleGate } from "@/components/RoleGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AlertTriangle, ArrowRight, BrainCircuit, ChevronLeft, Expand, FileCheck2, Layers3, MoveRight, Sigma } from "lucide-react";
import { useLocation } from "wouter";

const slideTypes = ["مفهوم", "تعريف", "صيغة", "خطوة بخطوة", "مثال", "مقارنة", "خطأ شائع", "نصيحة BAC", "نقطة تحقق", "خلاصة"];
export default function LearningLab() { return <RoleGate allowed={["student"]} title="مسار التعلم محمي"><LearningLabContent /></RoleGate>; }
function LearningLabContent() { const [, setLocation] = useLocation(); return <div className="min-h-screen bg-[#f6f8ff] p-5 sm:p-8" dir="rtl"><div className="mx-auto max-w-6xl"><button onClick={() => setLocation("/app")} className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowRight className="h-4 w-4"/>لوحة التعلم</button><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker">محركات التعلم</p><h1 className="mt-2 text-3xl font-black text-slate-950">من المساحة إلى الإتقان.</h1><p className="mt-2 text-sm leading-6 text-slate-600">واجهة تقنية للخرائط والشرائح والمعادلات. ستستقبل المحتوى فقط بعد اجتياز بوابة المصدر الحالي.</p></div><Badge className="border-0 bg-amber-50 px-3 py-2 text-amber-700 hover:bg-amber-50">لا يوجد محتوى أكاديمي منشور الآن</Badge></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><MindMapCanvas/><section className="soft-panel p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-black">محرك الشرائح</p><p className="mt-1 text-xs text-slate-500">فكرة واحدة أساسيًا في كل شريحة.</p></div><Layers3 className="h-5 w-5 text-blue-700"/></div><div className="mt-5 flex flex-wrap gap-2">{slideTypes.map((type, index) => <span key={type} className={`rounded-lg px-2.5 py-1.5 text-[11px] font-bold ${index === 2 ? "bg-blue-700 text-white" : "bg-slate-100 text-slate-600"}`}>{type}</span>)}</div><div className="mt-7 rounded-2xl bg-gradient-to-bl from-blue-950 to-indigo-900 p-6 text-white"><div className="flex items-center justify-between"><p className="text-xs font-bold text-blue-200">معاينة KaTeX مستقلة عن المحتوى الأكاديمي</p><Sigma className="h-5 w-5 text-cyan-200"/></div><div className="mt-6 rounded-xl bg-white/10 px-4 py-3 text-lg"><MathBlock expression="\\frac{a+b}{2} = \\bar{x}" block/></div><p className="mt-5 text-xs leading-6 text-blue-200">يتم عزل الاتجاه LTR للمعادلة عن الواجهة العربية لضمان ظهور الكسور والجذور والرموز العلمية بشكل صحيح.</p></div></section></div><section className="mt-6 grid gap-4 md:grid-cols-3"><EngineCard icon={BrainCircuit} title="خريطة قابلة للمس" text="تكبير، سحب، ملء الشاشة، ولوحة مفاتيح."/><EngineCard icon={Expand} title="عقد متعددة الأنواع" text="مفهوم، صيغة، طريقة، مثال، تنبيه، وخطأ شائع."/><EngineCard icon={FileCheck2} title="شرائح مركزة" text="نموذج موحد للدرس ومراجعة المحتوى قبل النشر."/></section><section className="mt-6 rounded-[1.5rem] border border-dashed border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-700"/><div><p className="font-black text-amber-950">هذه المحركات جاهزة لاستقبال المادة، وليست بديلاً عن الكتاب الرسمي.</p><p className="mt-1 text-sm leading-6 text-amber-800">سيبقى محتوى الرياضيات والفيزياء وعلوم الطبيعة والحياة غير منشور حتى يوفر المشرف مصدرًا رسميًا حاليًا ويكمل المراجعة البشرية.</p></div></div></section></div></div>; }
function EngineCard({ icon: Icon, title, text }: { icon: typeof BrainCircuit; title: string; text: string }) { return <div className="soft-panel p-5"><Icon className="h-5 w-5 text-blue-700"/><p className="mt-4 font-black">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>; }
