import { MathBlock } from "@/components/MathBlock";
import { MindMapCanvas } from "@/components/MindMapCanvas";
import { RoleGate } from "@/components/RoleGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { uxCopy } from "@/content/uxCopy";
import { AlertTriangle, ArrowRight, BrainCircuit, ChevronLeft, Expand, FileCheck2, Layers3, MoveRight, Sigma } from "lucide-react";
import { useLocation } from "wouter";

const slideTypes = ["مفهوم", "تعريف", "صيغة", "خطوة بخطوة", "مثال", "مقارنة", "خطأ شائع", "نصيحة BAC", "نقطة تحقق", "خلاصة"];
export default function LearningLab() { return <RoleGate allowed={["student", "admin"]} title="مسار التعلم محمي"><LearningLabContent /></RoleGate>; }
function LearningLabContent() { const [, setLocation] = useLocation(); return <div className="learning-workspace min-h-screen p-5 sm:p-8" dir="rtl"><div className="mx-auto max-w-6xl"><button onClick={() => setLocation("/app")} className="learning-back flex items-center gap-2 text-sm font-bold"><ArrowRight className="h-4 w-4"/>العودة إلى رحلتك</button><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="student-eyebrow">تعلم مترابط</p><h1 className="learning-title mt-2">{uxCopy.learning.mapTitle}</h1><p className="mt-2 max-w-2xl text-sm leading-7 student-muted">{uxCopy.learning.mapDescription} تظهر المادة فقط بعد اجتياز بوابة المصدر الحالية.</p></div><Badge className="learning-source-badge px-3 py-2">ينتظر محتوى أكاديميًا معتمدًا</Badge></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><MindMapCanvas/><section className="learning-surface p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-black">{uxCopy.learning.slidesTitle}</p><p className="mt-1 text-xs student-muted">فكرة واحدة واضحة في كل شريحة.</p></div><Layers3 className="h-5 w-5 text-[var(--student-primary)]"/></div><div className="mt-5 flex flex-wrap gap-2">{slideTypes.map((type, index) => <span key={type} className={`learning-slide-tag ${index === 2 ? "learning-slide-tag-active" : ""}`}>{type}</span>)}</div><div className="learning-equation-card mt-7 rounded-2xl p-6"><div className="flex items-center justify-between"><p className="text-xs font-bold text-cyan-100">معاينة رياضية مستقلة عن المحتوى الأكاديمي</p><Sigma className="h-5 w-5 text-cyan-200"/></div><div className="mt-6 rounded-xl bg-white/10 px-4 py-3 text-lg"><MathBlock expression="\\frac{a+b}{2} = \\bar{x}" block/></div><p className="mt-5 text-xs leading-6 text-cyan-100/75">تعزل المعادلة اتجاهها عن الواجهة العربية لتظهر الكسور والجذور والرموز العلمية بصورة صحيحة.</p></div></section></div><section className="mt-6 grid gap-4 md:grid-cols-3"><EngineCard icon={BrainCircuit} title="ارَ الصورة كاملة" text="كبّر الخريطة واسحبها وانتقل بين المفاهيم بوضوح."/><EngineCard icon={Expand} title="اتبع الفكرة" text="مفهوم وصيغة وطريقة ومثال وتنبيه وخطأ شائع."/><EngineCard icon={FileCheck2} title="خطوات مركزة" text="نموذج واضح للدرس ومراجعة للمحتوى قبل النشر."/></section><section className="learning-governance mt-6 rounded-[1.5rem] p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div><p className="font-black">هذه الأدوات تساعد على الفهم، لكنها لا تحل محل المصدر المعتمد.</p><p className="mt-1 text-sm leading-6">يبقى محتوى الرياضيات والفيزياء وعلوم الطبيعة والحياة غير منشور إلى أن يتوفر مصدر رسمي حالي وتكتمل المراجعة البشرية.</p></div></div></section></div></div>; }
function EngineCard({ icon: Icon, title, text }: { icon: typeof BrainCircuit; title: string; text: string }) { return <div className="learning-surface p-5"><Icon className="h-5 w-5 text-[var(--student-primary)]"/><p className="mt-4 font-black">{title}</p><p className="mt-1 text-xs leading-5 student-muted">{text}</p></div>; }
