import React, { useMemo, useState } from "react";
import { BrandMark } from "@/components/BrandMark";
import { RoleGate } from "@/components/RoleGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ClipboardPenLine, FilePenLine, ShieldCheck, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

type GrantPlanCode = "season_one_subject" | "season_two_subjects" | "season_three_subjects" | "hasm_one_subject" | "hasm_two_subjects" | "hasm_three_subjects";
type GrantSubject = "math" | "physics" | "natural_sciences";

const assignablePlans: Array<{ code: GrantPlanCode; label: string; count: number }> = [
  { code: "season_one_subject", label: "الموسم — مادة واحدة", count: 1 },
  { code: "season_two_subjects", label: "الموسم — مادتان", count: 2 },
  { code: "season_three_subjects", label: "الموسم — المواد الثلاث", count: 3 },
  { code: "hasm_one_subject", label: "الحسم — مادة واحدة", count: 1 },
  { code: "hasm_two_subjects", label: "الحسم — مادتان", count: 2 },
  { code: "hasm_three_subjects", label: "الحسم — المواد الثلاث", count: 3 },
];

const subjectChoices: Array<{ value: GrantSubject; label: string }> = [
  { value: "math", label: "الرياضيات" },
  { value: "physics", label: "الفيزياء" },
  { value: "natural_sciences", label: "علوم الطبيعة" },
];

export function EditorPage() { return <StaffWorkspace allowed={["admin", "content_editor"]} eyebrow="مساحة المحرر" title="حرّر المحتوى، ولا تتجاوز المراجعة." description="ينشئ المحرر العناصر في Draft ويرسلها للمراجعة، لكنه لا يملك مسار النشر النهائي." icon={FilePenLine} action="إنشاء مسودة" />; }
export function ReviewerPage() { return <StaffWorkspace allowed={["admin", "academic_reviewer"]} eyebrow="المراجعة الأكاديمية" title="اعتماد بشري قبل أي نشر." description="تتحقق المراجعة من المصدر الحالي، مطابقة المنهج، وصلاحية المحتوى قبل القرار الأكاديمي." icon={ClipboardPenLine} action="فتح طابور المراجعة" />; }
export function AdminPage() { return <RoleGate allowed={["admin"]} title="إدارة المنصة محمية"><AdminContent /></RoleGate>; }

function AdminContent() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const { data: plans, isLoading } = trpc.administration.planCatalog.useQuery();
  const { data: localPaymentStatus, isLoading: isLoadingPaymentStatus } = trpc.administration.localPaymentStatus.useQuery();
  const { data: releaseReadiness, isLoading: isLoadingReadiness } = trpc.administration.releaseReadiness.useQuery();
  const { data: assignmentAudit, isLoading: isLoadingAudit } = trpc.administration.planAssignmentAudit.useQuery({ limit: 20 });
  const { data: planChangeAudit, isLoading: isLoadingChangeAudit } = trpc.administration.planChangeAudit.useQuery({ limit: 20 });
  const [studentId, setStudentId] = useState("");
  const [planCode, setPlanCode] = useState<GrantPlanCode>("season_one_subject");
  const [subjects, setSubjects] = useState<GrantSubject[]>(["math"]);
  const [changeKind, setChangeKind] = useState<"manual_assignment" | "upgrade" | "promotion">("manual_assignment");
  const [changeNoteAr, setChangeNoteAr] = useState("");
  const selectedPlan = useMemo(() => assignablePlans.find(plan => plan.code === planCode)!, [planCode]);
  const selectedSubjectLimit = plans?.find(plan => plan.code === planCode)?.subjectLimit ?? selectedPlan.count;
  const allowedAssignmentSubjects = useMemo(() => {
    const configured = plans?.find(plan => plan.code === planCode)?.subjectBundle;
    const allowed = Array.isArray(configured) && configured.length ? configured : subjectChoices.map(subject => subject.value);
    return subjectChoices.filter(subject => allowed.includes(subject.value));
  }, [plans, planCode]);
  const assignment = trpc.administration.grantPlanAccess.useMutation({
    onSuccess: () => { void utils.administration.planAssignmentAudit.invalidate(); void utils.administration.planChangeAudit.invalidate(); },
  });
  const qualityEvidence = trpc.administration.recordReleaseQualityEvidence.useMutation({
    onSuccess: () => { void utils.administration.releaseReadiness.invalidate(); },
  });
  const isReady = /^\d+$/.test(studentId) && Number(studentId) > 0 && subjects.length === selectedSubjectLimit;
  const preview = trpc.administration.previewPlanAssignment.useQuery({ planCode, subjects }, { enabled: subjects.length === selectedSubjectLimit });
  const toggleSubject = (subject: GrantSubject) => setSubjects(current => current.includes(subject) ? current.filter(item => item !== subject) : [...current, subject]);
  const changePlan = (value: GrantPlanCode) => {
    const next = assignablePlans.find(plan => plan.code === value)!;
    const configured = plans?.find(plan => plan.code === value)?.subjectBundle;
    const allowed = Array.isArray(configured) && configured.length ? configured : subjectChoices.map(subject => subject.value);
    setPlanCode(value);
    setSubjects(current => current.filter(subject => allowed.includes(subject)).slice(0, plans?.find(plan => plan.code === value)?.subjectLimit ?? next.count));
  };

  return <div className="min-h-screen bg-[#f6f8ff]" dir="rtl">
    <header className="flex h-20 items-center justify-between border-b border-slate-200/70 bg-white px-5 sm:px-8"><BrandMark /><Button variant="outline" onClick={() => setLocation("/studio")} className="rounded-xl font-bold">العودة إلى الاستوديو</Button></header>
    <main className="mx-auto max-w-5xl p-5 sm:p-8">
      <section className="soft-panel p-7 sm:p-10"><p className="section-kicker">إدارة المنصة</p><h1 className="mt-2 text-3xl font-black text-slate-950">الاشتراكات جاهزة كهيكل وصول.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600">تعرض هذه الصفحة الحزم والأسعار الأولية القابلة للتعديل من مصدر البيانات، مع الاستحقاقات وحالة التفعيل. لا توجد بوابة دفع أو تحصيل في هذه المرحلة.</p><Badge className="mt-5 border-0 bg-emerald-50 px-3 py-2 text-emerald-700 hover:bg-emerald-50">Payment-ready · الدفع غير مفعّل</Badge></section>
      <ReleaseReadinessPanel readiness={releaseReadiness} loading={isLoadingReadiness} recording={qualityEvidence.isPending} onRecord={input => qualityEvidence.mutate(input)} />
      <section className="mt-6 rounded-[1.5rem] border border-amber-100 bg-amber-50/70 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-black text-slate-950">حد الدفع المحلي المستقبلي</p><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-700">{isLoadingPaymentStatus ? "جارٍ التحقق من حالة الدفع…" : localPaymentStatus?.messageAr ?? "لا توجد حالة دفع متاحة."}</p><p className="mt-2 text-xs font-bold text-amber-800">المستقبل المدعوم: {localPaymentStatus?.supportedFutureCapabilities.join("، ") ?? "—"}. هذه معلومات هيكلية فقط؛ لا يوجد إنشاء طلب دفع أو تأكيد أو تحصيل.</p></div><Badge variant="outline" className="shrink-0 border-amber-200 bg-white text-amber-800">{localPaymentStatus?.enabled ? "مفعّل" : "معطّل"}</Badge></div></section>
      <section className="mt-6 grid gap-4 md:grid-cols-3">{isLoading ? <div className="soft-panel p-5 text-sm text-slate-500">جارٍ تحميل الخطط…</div> : plans?.map(plan => <ProductConfigCard key={plan.id} plan={plan} />)}</section>
      <section className="mt-6 rounded-[1.5rem] border border-blue-100 bg-white p-5 sm:p-6"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-100 text-blue-700"><UsersRound className="h-5 w-5" /></div><div><p className="font-black text-slate-950">تعيين خطة وصول داخلي</p><p className="mt-1 text-sm leading-6 text-slate-600">إجراء تشغيلي محمي للمدير: يحفظ تعيين الخطة، ويمنح الحسم تلقائيًا لمواد باقة الموسم نفسها. لا يجمع معلومات دفع ولا يؤكد عملية تحصيل.</p></div></div>
        <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-slate-700">رقم الطالب الداخلي<input aria-label="رقم الطالب الداخلي" inputMode="numeric" value={studentId} onChange={event => setStudentId(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none ring-blue-300 focus:ring-2" placeholder="مثال: 42" /></label><label className="grid gap-2 text-sm font-bold text-slate-700">الخطة<select aria-label="خطة الوصول" value={planCode} onChange={event => changePlan(event.target.value as GrantPlanCode)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none ring-blue-300 focus:ring-2">{assignablePlans.map(plan => <option key={plan.code} value={plan.code}>{plan.label}</option>)}</select></label></div>
        <fieldset className="mt-5"><legend className="text-sm font-bold text-slate-700">اختر {selectedSubjectLimit} مادة/مواد بالضبط</legend><div className="mt-3 flex flex-wrap gap-2">{allowedAssignmentSubjects.map(subject => <button type="button" key={subject.value} aria-pressed={subjects.includes(subject.value)} onClick={() => toggleSubject(subject.value)} className={`rounded-xl border px-4 py-2 text-sm font-bold transition ${subjects.includes(subject.value) ? "border-blue-600 bg-blue-700 text-white" : "border-slate-200 bg-white text-slate-600 hover:border-blue-300"}`}>{subject.label}</button>)}</div></fieldset>
        <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-slate-700">نوع التغيير الداخلي<select aria-label="نوع تغيير الخطة" value={changeKind} onChange={event => setChangeKind(event.target.value as typeof changeKind)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none ring-blue-300 focus:ring-2"><option value="manual_assignment">تعيين تشغيلي يدوي</option><option value="upgrade">ترقية يوافق عليها المدير</option><option value="promotion">عرض داخلي موثق</option></select></label><label className="grid gap-2 text-sm font-bold text-slate-700">ملاحظة تغيير اختيارية<input aria-label="ملاحظة تغيير الخطة" value={changeNoteAr} onChange={event => setChangeNoteAr(event.target.value)} placeholder="سبب إداري؛ لا توجد بيانات دفع" className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none ring-blue-300 focus:ring-2" /></label></div>
        <div className="mt-6 flex flex-wrap items-center gap-3"><Button disabled={!isReady || assignment.isPending} onClick={() => assignment.mutate({ userId: Number(studentId), planCode, subjects, changeKind, noteAr: changeNoteAr.trim() || undefined })} className="h-11 rounded-xl bg-blue-700 px-5 font-black hover:bg-blue-800">{assignment.isPending ? "جارٍ حفظ التعيين…" : "حفظ التعيين ومنح الاستحقاقات"}</Button>{!isReady && <p className="text-xs font-bold text-amber-700">أدخل رقم طالب صحيحًا وطابق عدد المواد مع الخطة.</p>}</div>
        <div className="mt-4 rounded-xl border border-sky-100 bg-sky-50/60 p-4 text-sm text-slate-700"><p className="font-black text-sky-950">معاينة غير مُعدِّلة</p>{preview.isLoading ? <p className="mt-1 text-xs">جارٍ حساب الاستحقاقات…</p> : preview.data ? <p className="mt-1 text-xs leading-5">الخطة: {preview.data.plan.nameAr} · المواد: {preview.data.selectedSubjects.join("، ")} · الاستحقاقات المتوقعة: {preview.data.entitlements.join("، ") || "لا توجد"}. هذه المعاينة لا تحفظ تعيينًا ولا تمنح وصولًا.</p> : <p className="mt-1 text-xs">اختر عدد المواد المطابق للخطة لعرض معاينة بلا كتابة.</p>}</div>
        {assignment.data && <div className="mt-5 rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-950"><p className="font-black">تم الحفظ التشغيلي بنجاح.</p><p className="mt-1">الطبقة: {assignment.data.productTier} · الاستحقاقات: {assignment.data.entitlements.join("، ")}</p></div>}
        {assignment.error && <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-sm font-bold text-rose-800">تعذر حفظ التعيين: {assignment.error.message}</p>}
      </section>
      <section className="mt-6 rounded-[1.5rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-black text-slate-950">سجل تعيينات الوصول</p><p className="mt-1 text-sm leading-6 text-slate-600">عرض إداري للقراءة فقط: يوضح التعيينات المحفوظة والاستحقاقات المسجلة بالفعل، ولا يمنح أو يلغي أي وصول من هذه البطاقة.</p></div><Badge variant="outline" className="shrink-0 border-slate-200 text-slate-600">Read-only audit</Badge></div>{isLoadingAudit ? <p className="mt-5 text-sm text-slate-500">جارٍ تحميل السجل…</p> : assignmentAudit?.length ? <div className="mt-5 grid gap-3">{assignmentAudit.map(item => <div key={item.assignmentId} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black text-slate-900">طالب #{item.userId} · {item.planNameAr}</p><Badge variant="outline" className={item.isActive ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-slate-200 text-slate-500"}>{item.isActive ? "تعيين نشط" : "سجل سابق"}</Badge></div><p className="mt-2 text-xs text-slate-500">{item.productTier} · المواد: {Array.isArray(item.selectedSubjects) ? item.selectedSubjects.join("، ") : "غير متاح"}</p><p className="mt-2 text-xs leading-5 text-slate-600">الاستحقاقات المسجلة: {item.activeEntitlements.length ? item.activeEntitlements.map(claim => claim.entitlement).join("، ") : "لا توجد استحقاقات مسجلة"}</p></div>)}</div> : <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">لا توجد تعيينات محفوظة بعد. يظهر السجل هنا بعد إجراء تشغيلي من المدير.</p>}</section>
      <section className="mt-6 rounded-[1.5rem] border border-blue-100 bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-black text-slate-950">سجل العروض والترقيات الداخلي</p><p className="mt-1 text-sm leading-6 text-slate-600">سجل قراءة فقط للقرارات الإدارية المصرح بها. لا يسجل تحصيلًا، ولا يحتفظ ببطاقة أو مرجع دفع.</p></div><Badge variant="outline" className="shrink-0 border-blue-100 bg-blue-50 text-blue-700">Non-payment audit</Badge></div>{isLoadingChangeAudit ? <p className="mt-5 text-sm text-slate-500">جارٍ تحميل سجل التغييرات…</p> : planChangeAudit?.length ? <div className="mt-5 grid gap-3">{planChangeAudit.map(item => <div key={item.id} className="rounded-xl border border-blue-50 bg-blue-50/40 p-4"><p className="font-black text-slate-900">طالب #{item.userId} · {item.nextPlanNameAr}</p><p className="mt-2 text-xs text-slate-600">النوع: {item.changeKind === "upgrade" ? "ترقية" : item.changeKind === "promotion" ? "عرض داخلي" : "تعيين يدوي"} · منفذ القرار #{item.actorUserId}</p>{item.noteAr && <p className="mt-2 text-xs leading-5 text-slate-600">الملاحظة: {item.noteAr}</p>}</div>)}</div> : <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">لا توجد عروض أو ترقيات موثقة بعد.</p>}</section>
      <section className="mt-6 rounded-[1.5rem] border border-emerald-100 bg-emerald-50 p-6"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-600"/><p className="text-sm leading-6 text-emerald-900">تقرر طبقة الوصول بين «وحدة مجانية» و«مادة مشمولة بالاستحقاق» قبل إعادة أي محتوى منشور. يظهر كل تعيين محفوظ وسجل استحقاقاته للمراجعة الإدارية، بينما يبقى الدفع غير مفعّل بالكامل.</p></div></section>
    </main>
  </div>;
}

type CatalogPlan = { id: number; code: string; nameAr: string; priceDzd: number; durationDays?: number; subjectLimit?: number; subjectBundle?: string[]; isActive: boolean; entitlements: string[] };

type ReleaseCheckKey = "academic_batch_qa" | "real_account_qa" | "operational_qa" | "published_bac_session";
type ReleaseReadiness = { isReadOnly: true; technicalEvidence: { automatedTestCount: number; testFileCount: number; baselineTag: string; sourceBackupVerified: boolean; repositoryIntegrityVerified: boolean }; batch1: { inReviewPackages: number; componentCount: number; substantiveComponentCount: number; blockedComponentCount: number; publicationAllowed: boolean }; humanAcceptanceGates: Array<{ key: ReleaseCheckKey; labelAr: string; status: "required"; evidence: { latestEvidence: string | null; recordedAt: Date | null; actorUserId: number | null } | null }>; publicationGuard: string };

function ReleaseReadinessPanel({ readiness, loading, recording, onRecord }: { readiness?: ReleaseReadiness; loading: boolean; recording: boolean; onRecord: (input: { checkKey: ReleaseCheckKey; evidenceNoteAr: string }) => void }) {
  return <section className="mt-6 rounded-[1.5rem] border border-violet-100 bg-violet-50/60 p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-black text-slate-950">جاهزية الإصدار — قراءة فقط</p><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-600">تجمع هذه البطاقة الأدلة التقنية وبوابات القبول التي لا يمكن استبدالها بالمحاكاة. لا تحتوي على إجراء اعتماد أو نشر أو تعديل بيانات.</p></div><Badge variant="outline" className="w-fit border-violet-200 bg-white text-violet-700">Read-only evidence</Badge></div>{loading ? <p className="mt-5 text-sm text-slate-500">جارٍ تحميل أدلة الجاهزية…</p> : readiness ? <><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><ReadinessMetric label="الاختبارات الموثقة" value={`${readiness.technicalEvidence.automatedTestCount}/${readiness.technicalEvidence.testFileCount}`} /><ReadinessMetric label="حزم Batch 1 في المراجعة" value={String(readiness.batch1.inReviewPackages)} /><ReadinessMetric label="المكونات الجوهرية" value={`${readiness.batch1.substantiveComponentCount}/${readiness.batch1.componentCount}`} /><ReadinessMetric label="أقفال النشر" value={`${readiness.batch1.blockedComponentCount}/${readiness.batch1.componentCount}`} /></div><div className="mt-4 rounded-xl border border-violet-100 bg-white/80 p-4"><p className="text-xs font-black text-violet-900">دليل خط الأساس: {readiness.technicalEvidence.baselineTag} · نسخة احتياطية {readiness.technicalEvidence.sourceBackupVerified ? "متحقق منها" : "غير متاحة"} · سلامة المستودع {readiness.technicalEvidence.repositoryIntegrityVerified ? "متحقق منها" : "غير متاحة"}</p><p className="mt-2 text-xs leading-5 text-slate-600">{readiness.publicationGuard}</p></div><div className="mt-4 grid gap-2">{readiness.humanAcceptanceGates.map(gate => <div key={gate.key} className="rounded-xl border border-amber-100 bg-amber-50/70 p-3"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-amber-700" /><p className="text-xs font-bold leading-5 text-amber-900">مطلوب قبل القبول: {gate.labelAr}</p></div>{gate.evidence?.latestEvidence && <p className="mt-2 border-t border-amber-100 pt-2 text-xs leading-5 text-slate-700">آخر دليل مسجل: {gate.evidence.latestEvidence}</p>}</div>)}</div><ReleaseQualityEvidenceForm gates={readiness.humanAcceptanceGates} recording={recording} onRecord={onRecord} /></> : <p className="mt-5 text-sm text-rose-700">تعذر تحميل ملخص الجاهزية.</p>}</section>;
}

function ReleaseQualityEvidenceForm({ gates, recording, onRecord }: { gates: ReleaseReadiness["humanAcceptanceGates"]; recording: boolean; onRecord: (input: { checkKey: ReleaseCheckKey; evidenceNoteAr: string }) => void }) {
  const [checkKey, setCheckKey] = useState<ReleaseCheckKey>(gates[0]?.key ?? "academic_batch_qa"); const [evidenceNoteAr, setEvidenceNoteAr] = useState("");
  return <div className="mt-4 rounded-xl border border-slate-200 bg-white p-4"><p className="font-black text-slate-950">تسجيل دليل قبول يدوي</p><p className="mt-1 text-xs leading-5 text-slate-600">يحفظ هذا النموذج وصف الدليل وتاريخ المنفذ فقط. لا يعتمد مصدرًا أو محتوى ولا ينشر شيئًا.</p><div className="mt-3 grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)_auto]"><select aria-label="بوابة القبول" value={checkKey} onChange={event => setCheckKey(event.target.value as ReleaseCheckKey)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm">{gates.map(gate => <option key={gate.key} value={gate.key}>{gate.labelAr}</option>)}</select><input aria-label="دليل قبول يدوي" value={evidenceNoteAr} onChange={event => setEvidenceNoteAr(event.target.value)} placeholder="صف الحسابات أو المراجع أو رابط محضر المراجعة…" className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm" /><Button disabled={recording || evidenceNoteAr.trim().length < 10} onClick={() => onRecord({ checkKey, evidenceNoteAr: evidenceNoteAr.trim() })} className="bg-slate-950 font-black hover:bg-slate-800">{recording ? "جارٍ التسجيل…" : "تسجيل الدليل فقط"}</Button></div></div>;
}

function ReadinessMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-violet-100 bg-white p-3"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-xl font-black text-slate-950">{value}</p></div>; }

function ProductConfigCard({ plan }: { plan: CatalogPlan }) {
  const utils = trpc.useUtils();
  const [priceDzd, setPriceDzd] = useState(String(plan.priceDzd));
  const [durationDays, setDurationDays] = useState(String(plan.durationDays ?? 0));
  const [subjectLimit, setSubjectLimit] = useState(String(plan.subjectLimit ?? 0));
  const [subjectBundle, setSubjectBundle] = useState<GrantSubject[]>(() => (plan.subjectBundle ?? subjectChoices.map(subject => subject.value)).filter((subject): subject is GrantSubject => subject === "math" || subject === "physics" || subject === "natural_sciences"));
  const [isActive, setIsActive] = useState(plan.isActive);
  const [entitlements, setEntitlements] = useState(plan.entitlements.join(", "));
  const update = trpc.administration.updatePlanConfiguration.useMutation({ onSuccess: () => void utils.administration.planCatalog.invalidate() });
  const claims = entitlements.split(",").map(item => item.trim()).filter(Boolean);
  const valid = Number.isInteger(Number(priceDzd)) && Number(priceDzd) >= 0 && Number.isInteger(Number(durationDays)) && Number(durationDays) >= 0 && Number.isInteger(Number(subjectLimit)) && Number(subjectLimit) >= 0 && Number(subjectLimit) <= 3 && subjectBundle.length > 0 && Number(subjectLimit) <= subjectBundle.length;
  const toggleSubjectBundle = (subject: GrantSubject) => setSubjectBundle(current => current.includes(subject) ? current.filter(item => item !== subject) : [...current, subject]);

  return <div className="soft-panel p-5"><p className="text-xs font-bold text-slate-500">{plan.code}</p><h2 className="mt-3 font-black text-slate-950">{plan.nameAr}</h2><p className="mt-2 text-xl font-black text-blue-800">{Number(plan.priceDzd).toLocaleString("ar-DZ")} دج</p><p className="mt-2 text-xs text-slate-500">{plan.entitlements.length} صلاحيات · {plan.isActive ? "مفعّلة" : "موقوفة"}</p><div className="mt-4 flex flex-wrap gap-2">{plan.entitlements.map(item => <Badge key={item} variant="outline" className="border-blue-100 bg-blue-50 text-blue-700">{item}</Badge>)}</div>
    <details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-sm font-black text-blue-800">ضبط داخلي آمن</summary><div className="mt-4 grid gap-3"><label className="grid gap-1 text-xs font-bold text-slate-600">السعر بالدينار<input aria-label={`سعر ${plan.code}`} type="number" min="0" value={priceDzd} onChange={event => setPriceDzd(event.target.value)} className="h-10 rounded-lg border border-slate-200 bg-slate-50 px-2 text-sm" /></label><label className="grid gap-1 text-xs font-bold text-slate-600">مدة الوصول بالأيام (0 = وفق سياسة التشغيل)<input aria-label={`مدة ${plan.code}`} type="number" min="0" max="730" value={durationDays} onChange={event => setDurationDays(event.target.value)} className="h-10 rounded-lg border border-slate-200 bg-slate-50 px-2 text-sm" /></label><label className="grid gap-1 text-xs font-bold text-slate-600">حد المواد<input aria-label={`حد المواد ${plan.code}`} type="number" min="0" max="3" value={subjectLimit} onChange={event => setSubjectLimit(event.target.value)} className="h-10 rounded-lg border border-slate-200 bg-slate-50 px-2 text-sm" /></label><fieldset><legend className="text-xs font-bold text-slate-600">تشكيل المواد المسموح بها</legend><div className="mt-2 flex flex-wrap gap-2">{subjectChoices.map(subject => <button key={subject.value} type="button" aria-pressed={subjectBundle.includes(subject.value)} onClick={() => toggleSubjectBundle(subject.value)} className={`rounded-lg border px-3 py-1.5 text-xs font-bold ${subjectBundle.includes(subject.value) ? "border-blue-600 bg-blue-700 text-white" : "border-slate-200 bg-white text-slate-600"}`}>{subject.label}</button>)}</div></fieldset><label className="grid gap-1 text-xs font-bold text-slate-600">استحقاقات الميزات، مفصولة بفاصلة<input aria-label={`استحقاقات ${plan.code}`} value={entitlements} onChange={event => setEntitlements(event.target.value)} className="h-10 rounded-lg border border-slate-200 bg-slate-50 px-2 text-sm" /></label><label className="flex items-center gap-2 text-xs font-bold text-slate-700"><input aria-label={`تفعيل ${plan.code}`} type="checkbox" checked={isActive} onChange={event => setIsActive(event.target.checked)} />الحزمة مفعّلة</label><Button disabled={!valid || update.isPending} onClick={() => update.mutate({ id: plan.id, priceDzd: Number(priceDzd), durationDays: Number(durationDays), subjectLimit: Number(subjectLimit), subjectBundle, isActive, entitlements: claims })} className="h-10 rounded-lg bg-slate-950 text-xs font-black hover:bg-slate-800">{update.isPending ? "جارٍ الحفظ…" : "حفظ ضبط الحزمة"}</Button>{update.data && <p className="text-xs font-bold text-emerald-700">تم حفظ الضبط دون تنفيذ أي تحصيل.</p>}{update.error && <p role="alert" className="text-xs font-bold text-rose-700">تعذر الحفظ: {update.error.message}</p>}</div></details>
  </div>;
}

function StaffWorkspace({ allowed, eyebrow, title, description, icon: Icon, action }: { allowed: Array<"admin" | "content_editor" | "academic_reviewer">; eyebrow: string; title: string; description: string; icon: typeof FilePenLine; action: string }) {
  const [, setLocation] = useLocation();
  return <RoleGate allowed={allowed} title="مساحة عمل محمية"><div className="min-h-screen bg-[#f6f8ff]" dir="rtl"><header className="flex h-20 items-center justify-between border-b border-slate-200/70 bg-white px-5 sm:px-8"><BrandMark /><Button variant="outline" onClick={() => setLocation("/studio")} className="rounded-xl font-bold">العودة إلى الاستوديو</Button></header><main className="mx-auto max-w-5xl p-5 sm:p-8"><div className="soft-panel relative overflow-hidden p-7 sm:p-10"><div className="absolute left-0 top-0 h-40 w-40 rounded-full bg-blue-100/80 blur-3xl"/><div className="relative"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-950 text-white"><Icon className="h-6 w-6"/></div><p className="section-kicker mt-7">{eyebrow}</p><h1 className="mt-2 text-3xl font-black text-slate-950">{title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600">{description}</p><div className="mt-8 flex flex-wrap gap-3"><Button className="h-11 rounded-xl bg-blue-700 font-bold hover:bg-blue-800">{action}</Button><Badge className="border-0 bg-blue-50 px-3 py-2 text-blue-700 hover:bg-blue-50">لا يوجد نشر تلقائي بالذكاء الاصطناعي</Badge></div></div></div><section className="mt-6 grid gap-4 md:grid-cols-3"><Stub label="مسودات نشطة" value="0"/><Stub label="بانتظار قرار" value="0"/><Stub label="مصدر حالي معتمد" value="0"/></section><section className="mt-6 rounded-[1.5rem] border border-emerald-100 bg-emerald-50 p-6"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-600"/><p className="text-sm leading-6 text-emerald-900">جميع الأدوات متصلة بسير عمل محتوى مُرقّم المراحل. سيُتاح الإدخال الفعلي بعد رفع المصدر الرسمي الحالي والتحقق البشري منه.</p></div></section></main></div></RoleGate>;
}

function Stub({ label, value }: { label: string; value: string }) { return <div className="soft-panel p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-3 text-3xl font-black text-slate-950">{value}</p></div>; }
