import { BrandMark } from "@/components/BrandMark";
import { RoleGate } from "@/components/RoleGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ClipboardPenLine, FilePenLine, ShieldCheck, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

export function EditorPage() { return <StaffWorkspace allowed={["admin", "content_editor"]} eyebrow="مساحة المحرر" title="حرّر المحتوى، ولا تتجاوز المراجعة." description="ينشئ المحرر العناصر في Draft ويرسلها للمراجعة، لكنه لا يملك مسار النشر النهائي." icon={FilePenLine} action="إنشاء مسودة" />; }
export function ReviewerPage() { return <StaffWorkspace allowed={["admin", "academic_reviewer"]} eyebrow="المراجعة الأكاديمية" title="اعتماد بشري قبل أي نشر." description="تتحقق المراجعة من المصدر الحالي، مطابقة المنهج، وصلاحية المحتوى قبل القرار الأكاديمي." icon={ClipboardPenLine} action="فتح طابور المراجعة" />; }
export function AdminPage() { return <StaffWorkspace allowed={["admin"]} eyebrow="إدارة المنصة" title="الحوكمة والصلاحيات في يدك." description="يدير المدير الأدوار والسياسات وسجل المصادر والخطط، مع حظر أي تجاوز لحارس المصدر." icon={UsersRound} action="إدارة الأدوار" />; }

function StaffWorkspace({ allowed, eyebrow, title, description, icon: Icon, action }: { allowed: Array<"admin" | "content_editor" | "academic_reviewer">; eyebrow: string; title: string; description: string; icon: typeof FilePenLine; action: string }) {
  const [, setLocation] = useLocation();
  return <RoleGate allowed={allowed} title="مساحة عمل محمية"><div className="min-h-screen bg-[#f6f8ff]" dir="rtl"><header className="flex h-20 items-center justify-between border-b border-slate-200/70 bg-white px-5 sm:px-8"><BrandMark /><Button variant="outline" onClick={() => setLocation("/studio")} className="rounded-xl font-bold">العودة إلى الاستوديو</Button></header><main className="mx-auto max-w-5xl p-5 sm:p-8"><div className="soft-panel relative overflow-hidden p-7 sm:p-10"><div className="absolute left-0 top-0 h-40 w-40 rounded-full bg-blue-100/80 blur-3xl"/><div className="relative"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-950 text-white"><Icon className="h-6 w-6"/></div><p className="section-kicker mt-7">{eyebrow}</p><h1 className="mt-2 text-3xl font-black text-slate-950">{title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600">{description}</p><div className="mt-8 flex flex-wrap gap-3"><Button className="h-11 rounded-xl bg-blue-700 font-bold hover:bg-blue-800">{action}</Button><Badge className="border-0 bg-blue-50 px-3 py-2 text-blue-700 hover:bg-blue-50">لا يوجد نشر تلقائي بالذكاء الاصطناعي</Badge></div></div></div><section className="mt-6 grid gap-4 md:grid-cols-3"><Stub label="مسودات نشطة" value="0"/><Stub label="بانتظار قرار" value="0"/><Stub label="مصدر حالي معتمد" value="0"/></section><section className="mt-6 rounded-[1.5rem] border border-emerald-100 bg-emerald-50 p-6"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-600"/><p className="text-sm leading-6 text-emerald-900">جميع الأدوات متصلة بسير عمل محتوى مُرقّم المراحل. سيُتاح الإدخال الفعلي بعد رفع المصدر الرسمي الحالي والتحقق البشري منه.</p></div></section></main></div></RoleGate>;
}
function Stub({ label, value }: { label: string; value: string }) { return <div className="soft-panel p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-3 text-3xl font-black text-slate-950">{value}</p></div>; }
