import { RoleGate } from "@/components/RoleGate";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/contexts/ThemeContext";
import { trpc } from "@/lib/trpc";
import React from "react";
import { ArrowLeft, Bell, BookOpenCheck, BrainCircuit, Check, ChevronLeft, ClipboardCheck, Compass, FlaskConical, FunctionSquare, Leaf, Menu, Moon, Play, Sparkles, Sun, Target, TimerReset, UserRound, Zap } from "lucide-react";
import { useLocation } from "wouter";

type SubjectCode = "math" | "physics" | "natural_sciences";
type LearningItem = { id: number; subjectCode: string; titleAr: string; type: string; provenance: "official_current" | "user_approved_working_reference" };

const subjectStyles: Record<SubjectCode, { icon: typeof FunctionSquare; label: string; className: string; note: string }> = {
  math: { icon: FunctionSquare, label: "الرياضيات", className: "subject-math", note: "الدقة والمنطق" },
  physics: { icon: FlaskConical, label: "العلوم الفيزيائية", className: "subject-physics", note: "الطاقة والتجربة" },
  natural_sciences: { icon: Leaf, label: "علوم الطبيعة والحياة", className: "subject-sciences", note: "الحياة والترابط" },
};

const reviewCopy: Record<string, string> = { solution_reveal: "كُشفت لك خطوات الحل سابقًا", heavy_hint_usage: "استعملت تلميحات كثيرة هنا" };

export default function StudentHome() {
  const overview = trpc.curriculum.overview.useQuery();
  const learningItems = trpc.curriculum.studentLearningItems.useQuery();
  const progress = trpc.progress.summary.useQuery();
  return <RoleGate allowed={["student"]} title="لوحتك التعليمية تنتظرك"><StudentWorkspace data={overview.data} learningItems={learningItems.data} progress={progress.data} /></RoleGate>;
}

function StudentWorkspace({ data, learningItems, progress }: { data?: { curriculum: { academicYear: string } | null; subjects: Array<{ id: number; code: string; nameAr: string; taglineAr: string | null; sourceGate: string }> }; learningItems?: LearningItem[]; progress?: { errors: Array<{ id: number; errorType: string; occurrences: number }>; reviews: Array<{ id: number; reason: string }>; mastery: Array<{ conceptNameAr: string; status: string; score: string }> } }) {
  const [, setLocation] = useLocation();
  const smartAssessment = trpc.progress.smartAssessment.useQuery(undefined, { enabled: false });
  const subjects = data?.subjects?.length ? data.subjects : [
    { id: 1, code: "math", nameAr: "الرياضيات", taglineAr: "اختيار الطريق الصحيح قبل كثرة الحسابات.", sourceGate: "waiting_for_current_official_book" },
    { id: 2, code: "physics", nameAr: "العلوم الفيزيائية", taglineAr: "قبل القانون… افهم واش راه يصرا.", sourceGate: "waiting_for_current_official_book" },
    { id: 3, code: "natural_sciences", nameAr: "علوم الطبيعة والحياة", taglineAr: "الوثيقة تعطيك الأدلة… وأنت تبني الاستنتاج.", sourceGate: "waiting_for_current_official_book" },
  ];
  const current = learningItems?.[0];
  const style = subjectStyles[current?.subjectCode as SubjectCode] ?? subjectStyles.math;
  const reviewCount = progress?.reviews.length ?? 0;
  const waitingCount = subjects.filter(item => item.sourceGate !== "verified").length;

  return <div className="student-shell" dir="rtl">
    <DesktopRail navigate={setLocation} />
    <main className="min-h-screen pb-28 lg:mr-[5.75rem] lg:pb-10">
      <StudentHeader year={data?.curriculum?.academicYear ?? "2026–2027"} />
      <div className="mx-auto max-w-[1440px] px-4 sm:px-7 lg:px-10">
        <section className="student-hero relative overflow-hidden rounded-[2rem] px-5 py-6 sm:px-8 sm:py-8">
          <div className="student-hero-orb student-hero-orb-one" /><div className="student-hero-orb student-hero-orb-two" />
          <div className="relative grid gap-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div><p className="student-eyebrow"><Sparkles className="h-3.5 w-3.5" /> جلسة اليوم</p><h1 className="mt-4 max-w-3xl text-2xl font-black leading-tight sm:text-3xl lg:text-[2.15rem]">{reviewCount ? `خلّينا نثبت ${reviewCount} ${reviewCount === 1 ? "فكرة" : "أفكار"} قبل ما نفتح خطوة جديدة.` : "اليوم نثبت الفهم ونخلي الخطوة الجاية أوضح."}</h1><p className="mt-3 max-w-2xl text-sm leading-7 student-muted">{current ? `عندك نقطة جاهزة في ${style.label}: ${current.titleAr}` : "ابدأ من المادة التي تهمك؛ يظهر لك المسار الآمن حسب المحتوى المتاح."}</p></div><Button onClick={() => setLocation(reviewCount ? "/hassem" : "/subjects")} className="student-button h-12 rounded-2xl px-5 font-black">{reviewCount ? "ابدأ تثبيت اليوم" : "استكشف مسارك"}<ArrowLeft className="mr-2 h-4 w-4" /></Button></div>
        </section>
        <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.72fr)_minmax(290px,.78fr)]"><div className="space-y-6">
          <ContinueCard item={current} style={style} onClick={() => setLocation("/subjects")} />
          <section><SectionHeading eyebrow="مساراتك" title="المواد الثلاث" action="كل المواد" onClick={() => setLocation("/subjects")} /><div className="grid gap-4 md:grid-cols-3">{subjects.map(subject => <SubjectCard key={subject.code} subject={subject} available={learningItems?.filter(item => item.subjectCode === subject.code).length ?? 0} onClick={() => setLocation("/subjects")} />)}</div></section>
          <section className="grid gap-4 md:grid-cols-2"><ErrorNotebook errors={progress?.errors ?? []} onClick={() => setLocation("/hassem")} /><MasteryPanel mastery={progress?.mastery ?? []} /></section>
          <SmartReading isFetching={smartAssessment.isFetching} onAnalyze={() => smartAssessment.refetch()} data={smartAssessment.data} />
        </div><aside className="space-y-4"><ReviewToday reviews={progress?.reviews ?? []} onClick={() => setLocation("/hassem")} /><AttentionCard count={waitingCount} onClick={() => setLocation("/subjects")} /><BacFocusCard onClick={() => setLocation("/bac")} /></aside></div>
      </div>
    </main><MobileDock navigate={setLocation} />
  </div>;
}

function StudentHeader({ year }: { year: string }) { const { theme, setTheme } = useTheme(); return <header className="mx-auto flex h-[5.5rem] max-w-[1440px] items-center justify-between px-4 sm:px-7 lg:px-10"><div className="flex items-center gap-3"><button className="student-icon-button lg:hidden" aria-label="فتح قائمة الطالب"><Menu className="h-5 w-5" /></button><div><p className="text-xs font-bold student-muted">مساء الخير</p><p className="mt-0.5 text-sm font-black sm:text-base">جاهز نربحو خطوة اليوم؟</p></div></div><div className="flex items-center gap-2"><div className="hidden rounded-xl border border-[var(--student-border)] bg-[var(--student-surface)] p-1 sm:flex" aria-label="اختيار السمة">{(["light", "dark", "system"] as const).map(value => <button key={value} onClick={() => setTheme?.(value)} className={`rounded-lg px-2.5 py-1 text-[10px] font-black ${theme === value ? "bg-[var(--student-primary)] text-slate-950" : "student-muted"}`}>{value === "light" ? <Sun className="h-3.5 w-3.5" /> : value === "dark" ? <Moon className="h-3.5 w-3.5" /> : "تلقائي"}</button>)}</div><button className="student-icon-button" aria-label="التنبيهات"><Bell className="h-[1.1rem] w-[1.1rem]" /></button><div className="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-bl from-[var(--student-primary)] to-violet-500 text-slate-950"><UserRound className="h-4 w-4" /></div><span className="hidden text-[10px] font-bold student-muted lg:block">{year}</span></div></header>; }

function DesktopRail({ navigate }: { navigate: (path: string) => void }) { const entries = [{ icon: Compass, label: "الرئيسية", path: "/app", active: true }, { icon: BookOpenCheck, label: "المواد", path: "/subjects" }, { icon: Play, label: "تدرّب", path: "/assessment" }, { icon: TimerReset, label: "مراجعتي", path: "/hassem" }, { icon: Target, label: "BAC", path: "/bac" }]; return <aside className="student-rail fixed inset-y-0 right-0 z-40 hidden w-[5.75rem] flex-col items-center py-5 lg:flex"><button onClick={() => navigate("/")} className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--student-primary)] text-slate-950 shadow-[0_10px_30px_var(--student-glow)]" aria-label="رفيق الباك"><Sparkles className="h-5 w-5" /></button><nav className="mt-10 flex flex-1 flex-col gap-3">{entries.map(entry => <button key={entry.label} onClick={() => navigate(entry.path)} className={`student-rail-item ${entry.active ? "student-rail-active" : ""}`} aria-label={entry.label}><entry.icon className="h-5 w-5" /><span>{entry.label}</span></button>)}</nav><button onClick={() => navigate("/student")} className="student-rail-item" aria-label="الحساب"><UserRound className="h-5 w-5" /><span>حسابي</span></button></aside>; }

function ContinueCard({ item, style, onClick }: { item?: LearningItem; style: typeof subjectStyles.math; onClick: () => void }) { const Icon = style.icon; return <section className={`student-surface student-card-interactive ${style.className} overflow-hidden rounded-[1.75rem] p-5 sm:p-6`}><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-4"><div className="subject-icon grid h-12 w-12 shrink-0 place-items-center rounded-2xl"><Icon className="h-5 w-5" /></div><div><p className="student-eyebrow">كمل من وين وقفت</p><h2 className="mt-2 truncate text-lg font-black sm:text-xl">{item?.titleAr ?? "أول خطوة في مسارك"}</h2><p className="mt-1 text-xs leading-5 student-muted">{style.label} · {item?.type ?? "مسار تعلّم"} · خطوة خفيفة وواضحة</p></div></div><div className="progress-ring" aria-label="التقدم المتاح"><span>{item ? "الآن" : "—"}</span></div></div><div className="mt-6 flex items-center justify-between gap-3 border-t border-[var(--student-border)] pt-4"><span className="text-xs font-bold student-muted">{item ? "أكمل الفكرة ثم خذ قرارك التالي" : "اختر مادة لتظهر نقطة البداية"}</span><Button onClick={onClick} variant="ghost" className="h-9 rounded-xl px-3 font-black text-[var(--student-primary)] hover:bg-[var(--student-glow)] hover:text-[var(--student-primary)]">واصل <ChevronLeft className="mr-1 h-4 w-4" /></Button></div></section>; }

function SubjectCard({ subject, available, onClick }: { subject: { code: string; nameAr: string; taglineAr: string | null; sourceGate: string }; available: number; onClick: () => void }) { const style = subjectStyles[subject.code as SubjectCode] ?? subjectStyles.math; const Icon = style.icon; const ready = subject.sourceGate === "verified"; return <button onClick={onClick} className={`student-surface student-card-interactive ${style.className} min-h-[13.5rem] rounded-[1.6rem] p-5 text-right`}><div className="flex items-start justify-between"><div className="subject-icon grid h-11 w-11 place-items-center rounded-2xl"><Icon className="h-5 w-5" /></div><span className={`subject-state ${ready ? "subject-state-ready" : ""}`}>{ready ? "جاهز" : "مسار آمن"}</span></div><h3 className="mt-7 font-black">{subject.nameAr}</h3><p className="mt-1 text-xs font-bold student-muted">{style.note}</p><p className="mt-3 min-h-10 text-xs leading-5 student-muted">{subject.taglineAr}</p><div className="mt-4 flex items-center justify-between border-t border-[var(--student-border)] pt-3 text-xs font-bold"><span className="student-muted">{available ? `${available} عناصر متاحة` : "بانتظار نقطة متاحة"}</span><ChevronLeft className="h-4 w-4 text-[var(--subject)]" /></div></button>; }

function ReviewToday({ reviews, onClick }: { reviews: Array<{ id: number; reason: string }>; onClick: () => void }) { return <section className="student-surface review-panel rounded-[1.6rem] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-amber-400/15 text-amber-500"><TimerReset className="h-5 w-5" /></div><div><p className="font-black">مراجعة اليوم</p><p className="mt-0.5 text-[11px] student-muted">اللي يثبت اليوم يسهّل غدوة</p></div></div><span className="review-count">{reviews.length}</span></div><div className="mt-5 space-y-2.5">{reviews.length ? reviews.slice(0, 3).map((review, index) => <div className="rounded-2xl border border-amber-300/15 bg-amber-300/5 p-3" key={review.id}><div className="flex items-center justify-between"><span className="text-[10px] font-black text-amber-500">{index === 0 ? "الأولوية الآن" : "قريبًا"}</span><span className="text-[10px] student-muted">5 د</span></div><p className="mt-2 text-xs leading-5">{reviewCopy[review.reason] ?? "هذا الخطأ يحتاج تثبيتًا هادئًا"}</p></div>) : <div className="rounded-2xl border border-dashed border-[var(--student-border)] p-4 text-center"><Check className="mx-auto h-5 w-5 text-emerald-400" /><p className="mt-2 text-xs font-bold">ممتاز… ما عندك حتى مراجعة مستحقة الآن.</p><p className="mt-1 text-[11px] student-muted">لما نلقى فكرة تستحق التثبيت، نضعها هنا.</p></div>}</div><Button onClick={onClick} variant="ghost" className="mt-4 h-10 w-full rounded-xl bg-amber-400/12 font-black text-amber-500 hover:bg-amber-400/18 hover:text-amber-400">{reviews.length ? "ثبته الآن" : "شوف خطتك"}<ArrowLeft className="mr-2 h-4 w-4" /></Button></section>; }

function AttentionCard({ count, onClick }: { count: number; onClick: () => void }) { return <section className="student-surface rounded-[1.6rem] p-5"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-rose-400/12 text-rose-400"><Target className="h-5 w-5" /></div><div><p className="font-black">نقطة تحتاج اهتمامًا</p><p className="mt-1 text-xs leading-5 student-muted">{count ? `${count} مواد تنتظر التحقق من مصدر حالي؛ لهذا لا نفتح مسارًا غير آمن.` : "مساراتك المتاحة واضحة الآن."}</p></div></div><button onClick={onClick} className="mt-4 flex items-center gap-1 text-xs font-black text-rose-400">راجع حالة المواد <ChevronLeft className="h-3.5 w-3.5" /></button></section>; }
function BacFocusCard({ onClick }: { onClick: () => void }) { return <button onClick={onClick} className="student-bac-card student-card-interactive w-full rounded-[1.6rem] p-5 text-right"><div className="flex items-center justify-between"><span className="student-eyebrow">BAC Focus</span><Zap className="h-5 w-5 text-violet-300" /></div><p className="mt-5 text-lg font-black">لما تحتاج تركيز…<br />نقص الضجيج.</p><p className="mt-2 max-w-[15rem] text-xs leading-5 text-violet-100/70">نتائجك وخطة الإنقاذ تبقى مبنية على ما تسجله فعليًا.</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-black text-violet-200">ادخل وضع التركيز <ArrowLeft className="h-3.5 w-3.5" /></span></button>; }
function ErrorNotebook({ errors, onClick }: { errors: Array<{ id: number; errorType: string; occurrences: number }>; onClick: () => void }) { return <section className="student-surface rounded-[1.6rem] p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-rose-400/12 text-rose-400"><ClipboardCheck className="h-5 w-5" /></div><div><p className="font-black">دفتر أخطائي</p><p className="mt-0.5 text-[11px] student-muted">ما نقولكش خطأ فقط؛ نرجعك للسبب.</p></div></div>{errors.length ? <div className="mt-5 space-y-2">{errors.slice(0, 2).map(error => <div key={error.id} className="flex items-center justify-between rounded-xl bg-rose-400/7 px-3 py-2.5 text-xs"><span>{error.errorType}</span><span className="font-black text-rose-400">{error.occurrences}×</span></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-[var(--student-border)] p-4"><p className="text-xs font-black">ممتاز… ما عندك حتى خطأ محفوظ هنا.</p><p className="mt-1 text-[11px] leading-5 student-muted">لما نلقى خطأ يستحق المراجعة، نحفظه هنا.</p></div>}<button onClick={onClick} className="mt-4 text-xs font-black text-[var(--student-primary)]">راجع السبب <ChevronLeft className="mr-1 inline h-3.5 w-3.5" /></button></section>; }
function MasteryPanel({ mastery }: { mastery: Array<{ conceptNameAr: string; status: string; score: string }> }) { return <section className="student-surface rounded-[1.6rem] p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-emerald-400/12 text-emerald-400"><Target className="h-5 w-5" /></div><div><p className="font-black">تقدمك</p><p className="mt-0.5 text-[11px] student-muted">الإتقان يظهر مع الفهم والتطبيق.</p></div></div><div className="mt-5">{mastery.length ? mastery.slice(0, 3).map(item => <div className="mt-2 first:mt-0" key={item.conceptNameAr}><div className="flex justify-between text-[11px] font-bold"><span>{item.conceptNameAr}</span><span className="text-emerald-400">{item.score}%</span></div><div className="mastery-line mt-1.5"><span style={{ width: `${Math.min(100, Number(item.score))}%` }} /></div></div>) : <div className="rounded-2xl bg-emerald-400/7 p-4"><p className="text-xs font-bold">لما تكمل محاولاتك، يظهر هنا أثر فهمك.</p><p className="mt-1 text-[11px] student-muted">ما نستعجلوش النتيجة؛ نقرأ المسار كامل.</p></div>}</div></section>; }
function SmartReading({ isFetching, onAnalyze, data }: { isFetching: boolean; onAnalyze: () => void; data?: { strengths: string[]; attentionPoint: string; nextReview: string } }) { return <section className="student-reading rounded-[1.75rem] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="student-eyebrow"><BrainCircuit className="h-3.5 w-3.5" /> قراءتنا لمستواك</p><h2 className="mt-3 text-xl font-black">نحوّل محاولاتك إلى خطوة واضحة.</h2><p className="mt-2 max-w-2xl text-sm leading-6 student-muted">نقرأ المحاولات والتلميحات والخطوات المكشوفة وسجل الأخطاء فقط؛ لا نخترع حقائق عن الدرس.</p></div><Button onClick={onAnalyze} disabled={isFetching} className="student-button h-10 shrink-0 rounded-xl px-4 font-black">{isFetching ? "جارٍ القراءة…" : "حلّل أدائي"}</Button></div>{data && <div className="mt-5 grid gap-3 md:grid-cols-3"><ReadingChip label="قوي في" value={data.strengths[0] ?? "محاولاتك المسجلة"} tone="emerald" /><ReadingChip label="يحتاج اهتمام" value={data.attentionPoint} tone="coral" /><ReadingChip label="الخطوة التالية" value={data.nextReview} tone="cyan" /></div>}</section>; }
function ReadingChip({ label, value, tone }: { label: string; value: string; tone: "emerald" | "coral" | "cyan" }) { return <div className={`reading-chip reading-chip-${tone} rounded-2xl p-4`}><p className="text-xs font-black">{label}</p><p className="mt-2 text-xs leading-6 student-muted">{value}</p></div>; }
function SectionHeading({ eyebrow, title, action, onClick }: { eyebrow: string; title: string; action: string; onClick: () => void }) { return <div className="mb-4 flex items-end justify-between"><div><p className="student-eyebrow">{eyebrow}</p><h2 className="mt-2 text-xl font-black">{title}</h2></div><button onClick={onClick} className="text-xs font-black text-[var(--student-primary)]">{action} <ChevronLeft className="mr-1 inline h-3.5 w-3.5" /></button></div>; }
function MobileDock({ navigate }: { navigate: (path: string) => void }) { const entries = [{ icon: Compass, label: "الرئيسية", path: "/app" }, { icon: BookOpenCheck, label: "المواد", path: "/subjects" }, { icon: Play, label: "جلسة اليوم", path: "/hassem", central: true }, { icon: TimerReset, label: "مراجعتي", path: "/hassem" }, { icon: UserRound, label: "حسابي", path: "/student" }]; return <nav className="student-mobile-dock fixed inset-x-3 bottom-3 z-50 flex h-[4.5rem] items-center justify-around px-2 lg:hidden">{entries.map((entry, index) => <button key={entry.label} onClick={() => navigate(entry.path)} className={`student-mobile-nav ${index === 0 ? "student-mobile-active" : ""} ${entry.central ? "student-mobile-central" : ""}`}><entry.icon className="h-4 w-4" /><span>{entry.label}</span></button>)}</nav>; }
