import React, { useMemo, useState } from "react";
import { Search, ShieldCheck, UserRoundPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

type ReviewerRow = { id: number; name: string | null; email: string | null; role: "student" | "academic_reviewer"; lastSignedIn: Date | string | null };

export function AcademicReviewerDirectoryPanel() {
  const utils = trpc.useUtils();
  const { data, isLoading } = trpc.administration.academicReviewerDirectory.useQuery();
  const [query, setQuery] = useState("");
  const mutation = trpc.administration.setAcademicReviewerStatus.useMutation({ onSuccess: () => void utils.administration.academicReviewerDirectory.invalidate() });
  const rows = useMemo<ReviewerRow[]>(() => ((data ?? []) as ReviewerRow[]).filter(row => `${row.id} ${row.name ?? ""} ${row.email ?? ""}`.toLocaleLowerCase("ar").includes(query.trim().toLocaleLowerCase("ar"))), [data, query]);
  return <section className="mt-6 rounded-[1.5rem] border border-violet-100 bg-white p-5 sm:p-6" dir="rtl"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-100 text-violet-700"><UserRoundPlus className="h-5 w-5" /></div><div><p className="font-black text-slate-950">مركز مراجعي الأساتذة</p><p className="mt-1 text-sm leading-6 text-slate-600">يسجل الأستاذ دخوله أولًا، ثم يظهر هنا ليمنحه المدير دور المراجع الأكاديمي فقط. لا ينشئ المركز حسابات أو كلمات مرور ولا يفتح النشر.</p></div></div><div className="mt-4 rounded-xl border border-sky-100 bg-sky-50 p-3 text-sm text-sky-950"><ShieldCheck className="ml-2 inline h-4 w-4" />خطوات الأستاذ: تسجيل الدخول أولًا، ثم تعيين مراجع هنا، ثم الدخول إلى <b>/review</b> أو <b>/studio</b>. قفل النشر للطلاب باقٍ.</div><label className="relative mt-4 block"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input aria-label="بحث في حسابات المراجعين" value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث بالاسم أو البريد أو الرقم الداخلي" className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pr-10 pl-3 text-sm" /></label><div className="mt-4 overflow-hidden rounded-xl border border-slate-100">{isLoading ? <p className="p-4 text-sm text-slate-500">جارٍ تحميل الحسابات…</p> : rows.length ? rows.map(row => <div key={row.id} className="flex items-center justify-between gap-3 border-t border-slate-100 p-4"><div className="min-w-0"><p className="truncate font-black text-slate-900">{row.name || `حساب #${row.id}`}</p><p className="truncate text-xs text-slate-500">{row.email || `الرقم الداخلي #${row.id}`}</p></div><Button size="sm" variant={row.role === "academic_reviewer" ? "outline" : "default"} disabled={mutation.isPending} onClick={() => mutation.mutate({ userId: row.id, enabled: row.role !== "academic_reviewer" })} className={row.role === "academic_reviewer" ? "rounded-lg" : "rounded-lg bg-violet-700 hover:bg-violet-800"}>{row.role === "academic_reviewer" ? "إلغاء دور المراجع" : "تعيين مراجع"}</Button></div>) : <p className="p-4 text-sm text-slate-500">لا توجد حسابات مطابقة. اطلب من الأستاذ تسجيل الدخول أولًا.</p>}</div>{mutation.error && <p role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">تعذر تحديث الدور: {mutation.error.message}</p>}</section>;
}
