import React from "react";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowDownLeft, ArrowUpRight, ShieldCheck, WalletCards } from "lucide-react";

export function PartnerCreditPanel() {
  const { data, isLoading, error } = trpc.partners.creditSnapshot.useQuery();
  return <section className="mt-6 rounded-[1.75rem] border border-cyan-300/15 bg-cyan-300/[0.06] p-5 sm:p-7" aria-labelledby="partner-credit-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/15 text-cyan-100"><WalletCards className="h-5 w-5" /></div><div><h2 id="partner-credit-title" className="font-black">رصيد B التشغيلي</h2><p className="mt-1 text-sm leading-6 text-slate-300">عرض رصيد مملوك لحسابك فقط. لا يمكن شراؤه أو تحويله أو استخدامه لمنح اشتراك من هذه الصفحة.</p></div></div><Badge className="border-0 bg-cyan-300/15 text-cyan-50 hover:bg-cyan-300/15">مغلق ماليًا</Badge></div>
    {isLoading ? <p className="mt-5 text-sm text-slate-300">جارٍ تحميل الرصيد…</p> : error || !data ? <p className="mt-5 rounded-xl border border-amber-300/15 bg-amber-300/[0.07] p-4 text-sm text-amber-100">لا يتوفر سجل رصيد B لهذا الحساب بعد.</p> : <><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-xs font-bold text-cyan-100">المتاح</p><p className="mt-2 text-3xl font-black">{data.availableCredits}</p><p className="mt-1 text-xs text-slate-300">وحدة تشغيلية</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-xs font-bold text-cyan-100">المحجوز</p><p className="mt-2 text-3xl font-black">{data.reservedCredits}</p><p className="mt-1 text-xs text-slate-300">لا تُضاف تلقائيًا</p></div></div><div className="mt-5"><p className="font-black">سجل القيود</p>{data.entries.length ? <div className="mt-3 grid gap-2">{data.entries.map(entry => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/15 p-3"><div className="flex items-center gap-2">{entry.entryType === "credit" ? <ArrowUpRight className="h-4 w-4 text-emerald-200" /> : <ArrowDownLeft className="h-4 w-4 text-rose-200" />}<div><p className="text-sm font-bold">{entry.entryType === "credit" ? "إضافة رصيد" : "خصم رصيد"} · {entry.amount} وحدة</p><p className="mt-1 text-xs text-slate-300">{entry.reasonAr}</p></div></div><p className="text-xs text-cyan-100">الرصيد بعد العملية: {entry.balanceAfter}</p></div>)}</div> : <p className="mt-3 rounded-xl border border-dashed border-white/15 p-4 text-sm text-slate-300">لا توجد قيود رصيد بعد.</p>}</div><p className="mt-5 flex gap-2 text-xs leading-5 text-slate-300"><ShieldCheck className="h-4 w-4 shrink-0 text-cyan-200" />هذه القيود لا تمثل دفعة أو فاتورة أو وصولًا أو اشتراكًا.</p></>}
  </section>;
}
