import React, { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export function ReviewOnlyVisualModels() {
  const [decay, setDecay] = useState<"alpha" | "beta">("alpha");
  const [proteinState, setProteinState] = useState<"folded" | "altered">("folded");
  const decayCopy = decay === "alpha" ? { symbol: "α", title: "مسار ألفا — مسودة مراجعة", detail: "تظهر الحالة المختارة كتمثيل بصري داخلي فقط؛ يثبت المراجع الاصطلاح والتسلسل قبل أي اعتماد." } : { symbol: "β−", title: "مسار بيتا السالب — مسودة مراجعة", detail: "يُستخدم النموذج لاختبار وضوح التمييز البصري، وليس لتقديم تعريف أكاديمي منشور." };
  const proteinCopy = proteinState === "folded" ? { title: "بنية مطوية — مسودة مراجعة", detail: "تبيّن البطاقة حالة ارتباط محتملة ضمن نموذج واجهة مراجعة فقط." } : { title: "تغيّر في البنية — مسودة مراجعة", detail: "تبيّن البطاقة أثر تغيير البنية على موقع ارتباط تمثيلي؛ تحتاج دقة العلاقة العلمية مراجعة بشرية." };
  return <section className="soft-panel mt-6 overflow-hidden" aria-label="نماذج بصرية تفاعلية قيد المراجعة">
    <div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">نماذج بصرية تفاعلية داخلية</h2><p className="mt-1 text-xs leading-5 text-slate-500">نسختان أصليتان للاختبار البصري في Studio. لا تدخلان مسار الطالب ولا تمثلان محتوى منشورًا.</p></div><Badge variant="outline" className="border-rose-100 bg-rose-50 text-rose-700">مقيدة بالمراجعة الأكاديمية</Badge></div>
    <div className="grid gap-5 p-5 lg:grid-cols-2">
      <article className="rounded-2xl border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-blue-700">الفيزياء · التحولات النووية</p><h3 className="mt-1 font-black text-slate-950">النموذج التفاعلي لمسار التحول</h3></div><Badge className="border-0 bg-violet-100 text-violet-700 hover:bg-violet-100">v1.1.0</Badge></div><div className="mt-5 grid min-h-40 place-items-center rounded-2xl bg-[#071d3f] p-5 text-center text-white"><div><div className="mx-auto grid h-20 w-20 place-items-center rounded-full border-4 border-cyan-300 bg-blue-950 text-3xl font-black">N</div><div className="mx-auto mt-3 w-28 border-t-2 border-dashed border-cyan-300" /><div className="mt-2 text-2xl font-black text-cyan-200">{decayCopy.symbol}</div></div></div><div className="mt-4 flex gap-2"><Button size="sm" variant={decay === "alpha" ? "default" : "outline"} onClick={() => setDecay("alpha")}>ألفا</Button><Button size="sm" variant={decay === "beta" ? "default" : "outline"} onClick={() => setDecay("beta")}>بيتا السالب</Button></div><p className="mt-4 text-sm font-bold text-slate-800">{decayCopy.title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{decayCopy.detail}</p><p className="mt-3 text-[10px] font-bold text-slate-500">الأصل: Batch 1 / مرجع الفيزياء الداخلي / حالة المصدر: historical_official / النشر محظور.</p></article>
      <article className="rounded-2xl border border-emerald-100 bg-gradient-to-br from-emerald-50 to-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-emerald-700">علوم الطبيعة · بنية–وظيفة البروتين</p><h3 className="mt-1 font-black text-slate-950">النموذج التفاعلي للبنية والارتباط</h3></div><Badge className="border-0 bg-violet-100 text-violet-700 hover:bg-violet-100">v1.1.0</Badge></div><div className="mt-5 flex min-h-40 items-center justify-center rounded-2xl bg-emerald-950 p-5"><div className={`relative h-24 w-40 transition-transform duration-200 ${proteinState === "altered" ? "rotate-6 scale-95" : "-rotate-3"}`}><div className="absolute inset-0 rounded-[45%_55%_40%_60%] bg-gradient-to-br from-emerald-200 via-cyan-300 to-emerald-500 shadow-lg" /><div className={`absolute left-1/2 top-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 ${proteinState === "folded" ? "border-amber-200 bg-amber-500" : "border-rose-200 bg-rose-500"}`} /></div></div><div className="mt-4 flex gap-2"><Button size="sm" variant={proteinState === "folded" ? "default" : "outline"} onClick={() => setProteinState("folded")}>بنية مطوية</Button><Button size="sm" variant={proteinState === "altered" ? "default" : "outline"} onClick={() => setProteinState("altered")}>تغيّر بنيوي</Button></div><p className="mt-4 text-sm font-bold text-slate-800">{proteinCopy.title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{proteinCopy.detail}</p><p className="mt-3 text-[10px] font-bold text-slate-500">الأصل: Batch 1 / مرجع العلوم الداخلي / حالة المصدر: historical_official / النشر محظور.</p></article>
    </div>
  </section>;
}
