import React, { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

function ReviewBadge() { return <><Badge className="border-0 bg-violet-100 text-violet-700 hover:bg-violet-100">v1.1.0</Badge><p className="mt-3 text-[10px] font-bold text-slate-500">Batch 1 · مرجع عمل داخلي historical_official · النشر محظور.</p></>; }

export function ReviewOnlyVisualModels() {
  const [reactionStage, setReactionStage] = useState<"start" | "progress">("start");
  const [decay, setDecay] = useState<"alpha" | "beta">("alpha");
  const [pathStep, setPathStep] = useState<"dna" | "rna" | "protein">("dna");
  const [proteinState, setProteinState] = useState<"folded" | "altered">("folded");
  const reactionCopy = reactionStage === "start" ? "بداية التحول — مسودة مراجعة" : "تقدّم التحول — مسودة مراجعة";
  const decayCopy = decay === "alpha" ? "مسار ألفا — مسودة مراجعة" : "مسار بيتا السالب — مسودة مراجعة";
  const pathCopy = pathStep === "dna" ? "نقطة DNA — مسودة مراجعة" : pathStep === "rna" ? "نقطة RNA — مسودة مراجعة" : "نقطة البروتين — مسودة مراجعة";
  const proteinCopy = proteinState === "folded" ? "بنية مطوية — مسودة مراجعة" : "تغيّر في البنية — مسودة مراجعة";
  return <section className="soft-panel mt-6 overflow-hidden" aria-label="نماذج بصرية تفاعلية قيد المراجعة">
    <div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">نماذج بصرية تفاعلية داخلية</h2><p className="mt-1 text-xs leading-5 text-slate-500">أربعة نماذج أصلية، نموذج لكل وحدة فيزياء وعلوم ضمن Batch 1. لا تدخل مسار الطالب ولا تمثل محتوى منشورًا.</p></div><Badge variant="outline" className="border-rose-100 bg-rose-50 text-rose-700">مقيدة بالمراجعة الأكاديمية</Badge></div>
    <div className="grid gap-4 p-5 lg:grid-cols-2">
      <article className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-blue-700">الفيزياء · تطور كميات المتفاعلات والنواتج</p><h3 className="mt-1 font-black text-slate-950">تقدّم التفاعل</h3></div><ReviewBadge /></div><div className="mt-4 rounded-xl bg-white p-4"><div className="flex h-12 items-end gap-2"><span className={`w-1/3 rounded-t bg-rose-400 transition-all ${reactionStage === "progress" ? "h-3" : "h-10"}`} /><span className={`w-1/3 rounded-t bg-cyan-500 transition-all ${reactionStage === "progress" ? "h-9" : "h-3"}`} /><span className="h-1 w-1/3 bg-slate-200" /></div><p className="mt-3 text-sm font-bold text-slate-800">{reactionCopy}</p></div><div className="mt-3 flex gap-2"><Button size="sm" variant={reactionStage === "start" ? "default" : "outline"} onClick={() => setReactionStage("start")}>البداية</Button><Button size="sm" variant={reactionStage === "progress" ? "default" : "outline"} onClick={() => setReactionStage("progress")}>التقدّم</Button></div><p className="mt-3 text-xs leading-5 text-slate-600">نموذج واجهة لاختبار وضوح التغيّر البصري فقط؛ يراجع مختص الفيزياء المعنى والاصطلاح.</p></article>
      <article className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-blue-700">الفيزياء · التحولات النووية</p><h3 className="mt-1 font-black text-slate-950">مسار التحول</h3></div><ReviewBadge /></div><div className="mt-4 grid h-28 place-items-center rounded-xl bg-[#071d3f] text-white"><div className="text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full border-4 border-cyan-300 bg-blue-950 font-black">N</div><div className="mt-2 text-xl font-black text-cyan-200">{decay === "alpha" ? "α" : "β−"}</div></div></div><div className="mt-3 flex gap-2"><Button size="sm" variant={decay === "alpha" ? "default" : "outline"} onClick={() => setDecay("alpha")}>ألفا</Button><Button size="sm" variant={decay === "beta" ? "default" : "outline"} onClick={() => setDecay("beta")}>بيتا السالب</Button></div><p className="mt-3 text-sm font-bold text-slate-800">{decayCopy}</p><p className="mt-2 text-xs leading-5 text-slate-600">التمييز البصري داخلي ولا يقدم تعريفًا منشورًا قبل اعتماد المراجع.</p></article>
      <article className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-emerald-700">علوم الطبيعة · تركيب البروتين</p><h3 className="mt-1 font-black text-slate-950">مسار DNA إلى البروتين</h3></div><ReviewBadge /></div><div className="mt-4 flex items-center justify-between rounded-xl bg-emerald-950 p-5 text-xs font-black text-white"><span className={pathStep === "dna" ? "text-amber-200" : "text-emerald-100"}>DNA</span><span>←</span><span className={pathStep === "rna" ? "text-amber-200" : "text-emerald-100"}>RNA</span><span>←</span><span className={pathStep === "protein" ? "text-amber-200" : "text-emerald-100"}>Protein</span></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant={pathStep === "dna" ? "default" : "outline"} onClick={() => setPathStep("dna")}>DNA</Button><Button size="sm" variant={pathStep === "rna" ? "default" : "outline"} onClick={() => setPathStep("rna")}>RNA</Button><Button size="sm" variant={pathStep === "protein" ? "default" : "outline"} onClick={() => setPathStep("protein")}>البروتين</Button></div><p className="mt-3 text-sm font-bold text-slate-800">{pathCopy}</p><p className="mt-2 text-xs leading-5 text-slate-600">تُراجع دقة التسلسل والحدود التبسيطية أكاديميًا قبل أي استخدام تعليمي.</p></article>
      <article className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-emerald-700">علوم الطبيعة · بنية–وظيفة البروتين</p><h3 className="mt-1 font-black text-slate-950">البنية والارتباط</h3></div><ReviewBadge /></div><div className="mt-4 flex h-28 items-center justify-center rounded-xl bg-emerald-950"><div className={`relative h-20 w-32 transition-transform duration-200 ${proteinState === "altered" ? "rotate-6 scale-95" : "-rotate-3"}`}><div className="absolute inset-0 rounded-[45%_55%_40%_60%] bg-gradient-to-br from-emerald-200 via-cyan-300 to-emerald-500 shadow-lg" /><div className={`absolute left-1/2 top-1/2 h-7 w-7 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 ${proteinState === "folded" ? "border-amber-200 bg-amber-500" : "border-rose-200 bg-rose-500"}`} /></div></div><div className="mt-3 flex gap-2"><Button size="sm" variant={proteinState === "folded" ? "default" : "outline"} onClick={() => setProteinState("folded")}>بنية مطوية</Button><Button size="sm" variant={proteinState === "altered" ? "default" : "outline"} onClick={() => setProteinState("altered")}>تغيّر بنيوي</Button></div><p className="mt-3 text-sm font-bold text-slate-800">{proteinCopy}</p><p className="mt-2 text-xs leading-5 text-slate-600">تمثيل واجهة لمراجعة وضوح العلاقة فقط؛ لا يثبت علاقة سببية قبل اعتماد المراجع.</p></article>
    </div>
  </section>;
}
