export const uxCopy = {
  brand: {
    name: "رفيق الباك الذكي",
    tagline: "افهم أكثر. تدرّب بذكاء. اقترب من هدفك.",
    parentNote: "لا نريد وقتًا أطول للدراسة؛ نريد وقتًا في المكان الصحيح.",
  },
  home: {
    eyebrow: "بكالوريا 2027 · علوم تجريبية",
    title: "لكل فكرة مسار أوضح.",
    accentTitle: "افهمها. طبّقها. ثبّتها.",
    description: "خريطة تعلم قصيرة تقودك إلى الخطوة التالية.",
    primaryCta: "ابدأ رحلتك مجانًا",
    secondaryCta: "اكتشف كيف نرتّب طريقك",
    subjectsEyebrow: "ابدأ من حاجتك الآن",
    subjectsTitle: "لكل مادة طريق واضح.",
    errorEyebrow: "الخطأ يضيء الطريق",
    errorTitle: "نعود إلى سبب الخطأ.",
    diagnosticTitle: "اكتشف ما يحتاج تركيزك.",
    diagnosticDescription: "تشخيص قصير يوضح أولويتك.",
    hassemTitle: "راجع بتركيز.",
    hassemDescription: "ثبّت المهم بخطة أوضح.",
  },
  student: {
    greetingTitle: "أهلًا بعودتك. لنكمل ما بدأناه.",
    greetingLabel: "خطوة اليوم",
    missionLabel: "خطوتك التالية",
    missionWithReviews: (count: number) => `لديك ${count} ${count === 1 ? "فكرة" : "أفكار"} تستحق دقائق من التركيز قبل الخطوة التالية.`,
    missionEmpty: "خطوة صغيرة اليوم تجعل طريق الغد أوضح.",
    continueEyebrow: "نكمل من هنا؟",
    continueFallback: "نقطة البداية في انتظارك",
    continueDescription: "آخر نقطة وصلت إليها، مع خطوة واضحة للمتابعة.",
    continueAction: "واصل التعلم",
    pathsEyebrow: "مساراتك الآن",
    pathsTitle: "ابدأ من المادة التي تحتاجها الآن",
    reviewTitle: "راجع ما يحتاجك اليوم",
    reviewEmptyTitle: "لا توجد مراجعة مستحقة الآن.",
    reviewEmptyDescription: "عندما تظهر فكرة تستحق العودة إليها، ستجدها هنا.",
    reviewAction: "ابدأ المراجعة",
    attentionTitle: "هذه النقطة تحتاج انتباهك",
    errorTitle: "دفتر ما يجب ألا يتكرر",
    errorEmptyTitle: "لا توجد أخطاء محفوظة هنا بعد.",
    errorEmptyDescription: "واصل التدريب؛ سنحتفظ لك بالأفكار التي تستحق العودة إليها.",
    masteryTitle: "أنت تتقدم، وهذه هي وجهتك",
    masteryEmptyTitle: "سيظهر أثر فهمك هنا مع محاولاتك.",
    smartTitle: "نحوّل محاولاتك إلى خطوتك التالية.",
    smartAction: "اقرأ أدائي",
    bacTitle: "الآن وقت التركيز.",
    bacDescription: "قلّل المشتتات وخض المحاكاة بهدوء، كما لو كنت في يوم البكالوريا.",
  },
  subjects: {
    math: ["حوّل الأرقام إلى منطق.", "ابدأ بالعلاقة قبل الحساب."],
    physics: ["افهم الظاهرة قبل أن تحفظ القانون.", "اربط المعطيات بما يحدث فعلًا."],
    naturalSciences: ["اربط التفاصيل بالصورة الكاملة.", "دع الأدلة تقودك إلى الاستنتاج."],
  },
  learning: {
    mapTitle: "ارَ الصورة كاملة",
    mapDescription: "اربط المفاهيم، وافهم أين تبدأ الفكرة وإلى أين تقودك.",
    slidesTitle: "افهمها خطوة بخطوة",
    exerciseTitle: "اختبر فهمك قبل أن تختبرك البكالوريا",
    exerciseCta: "جرّب بنفسك",
    correct: "أحسنت، فهمت الفكرة.",
    incorrect: "قريب جدًا. لنراجع الخطوة التي صنعت الفرق.",
    errorTitle: "الخطأ ليس مشكلة إذا عرفت سببه.",
  },
  hassem: {
    eyebrow: "الآن وقت الحسم",
    title: "من المراجعة العشوائية إلى خطة واضحة.",
    description: "رتّب ما تعلمته، ثبّت نقاط ضعفك، واعرف ما يحتاج وقتك الآن.",
    primaryCta: "ابدأ مرحلة الحسم",
  },
  bac: {
    startTitle: "الآن وقت التركيز.",
    startDescription: "أغلق المشتتات، وخض المحاكاة كما لو أنك في يوم البكالوريا.",
    startCta: "ابدأ المحاكاة",
    resultTitle: "انتهت المحاكاة. الآن نقرأ نتيجتك.",
  },
  pricing: {
    trial: { title: "جرّب قبل أن تقرر.", cta: "ابدأ التجربة" },
    season: { title: "ابنِ مستواك طوال الموسم.", cta: "ابدأ موسمك" },
    hassem: { title: "حوّل ما تعلمته إلى استعداد حقيقي.", cta: "ابدأ مرحلة الحسم" },
  },
  system: {
    retry: "إعادة المحاولة",
    unexpectedError: "حدث خطأ غير متوقع. لم نفقد تقدمك؛ حاول مرة أخرى.",
    signInTitle: "أكمل رحلتك.",
    signInDescription: "تقدمك ومراجعاتك محفوظة هنا.",
    signInCta: "الدخول إلى حسابي",
  },
  motivation: [
    "كل فكرة تفهمها اليوم توفر عليك ارتباكًا غدًا.",
    "لا تحتاج إلى دراسة كل شيء الآن؛ تحتاج إلى معرفة ما تبدأ به.",
    "الفهم الجيد يجعل المراجعة أسرع.",
    "خطوة صغيرة اليوم تصنع فرقًا واضحًا لاحقًا.",
    "عندما تفهم الخطأ، تكون قد قطعت نصف الطريق.",
    "المراجعة الذكية ليست وقتًا أكثر، بل اختيارًا أفضل.",
  ],
} as const;

export function subjectCopy(code: string, variant = 0) {
  const copy = code === "math" ? uxCopy.subjects.math : code === "physics" ? uxCopy.subjects.physics : uxCopy.subjects.naturalSciences;
  return copy[variant % copy.length];
}
